[source]
git = "https://gitlab.redox-os.org/redox-os/redox.git"

[build]
template = "custom"
script = """
cookbook_cargo

mkdir -pv "${COOKBOOK_STAGE}/home/user/cookbook"
cp -rv "${COOKBOOK_SOURCE}"/* "${COOKBOOK_STAGE}/home/user/cookbook"
"""

[package]
# Dependencies below does not include Rust / GCC
#   because it will be downloaded as prefix binary.
dependencies = [
    "autoconf",
    "automake",
    "git",
    "cbindgen",
    "gnu-binutils",
    "gnu-grep",
    "gnu-make",
    "installer",
    "nasm",
    "pkg-config",
    "pkgar",
    "rustpython",
    "sed",
    "wget",
]
