# Configuration for automated testing of essential test suites
# Smaller test suites are executed first to catch possible bugs or regressions faster

include = ["base.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 1024

# Package settings
[packages]
auto-test = {}

[[files]]
path = "/usr/lib/init.d/30_console"
data = """
requires_weak 10_net
ion /usr/lib/run_tests.ion
"""

[[files]]
path = "/usr/lib/run_tests.ion"
data = """
#!/usr/bin/env ion
export RUST_BACKTRACE=full
cd /home/user/acid
cargo test
bash /root/relibc-tests/run.sh
os-test-runner
shutdown
"""
