# Configuration for the Redoxer GUI image

include = ["redoxer.toml"]

# Package settings
[packages]
orbdata = {}
orbital = {}

# Override to run inside of orbital
[[files]]
path = "/usr/lib/init.d/30_redoxer"
data = """
requires_weak 10_net
echo
echo "## running redoxer in orbital ##"
nowait VT=3 orbital redoxerd
"""
