# Server configuration

include = ["minimal.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 512

# Package settings
[packages]
bash = {}
bottom = {}
#contain = {} # needs to update dependencies
curl = {}
diffutils = {}
findutils = {}
git = {}
installer = {}
kibi = {}
redoxfs = {}
