[llvm]
download-ci-llvm = false
static-libstdcpp = false
targets = "X86"
experimental-targets = ""
link-shared = true

[build]
host = ["x86_64-unknown-redox"]
target = ["x86_64-unknown-redox"]
submodules = false
docs = false
tools = ["cargo", "clippy", "rustdoc", "rustfmt", "src"]
extended = true
verbose = 1

[install]
prefix = "install"
sysconfdir = "etc"

[rust]
backtrace = false
codegen-tests = false

[target.x86_64-unknown-redox]
cc = "x86_64-unknown-redox-gcc"
cxx = "x86_64-unknown-redox-g++"
ar = "x86_64-unknown-redox-ar"
linker = "x86_64-unknown-redox-gcc"
rpath = false
crt-static = false
llvm-config = "COOKBOOK_SYSROOT/bin/llvm-config"

[target.aarch64-unknown-linux-gnu]
llvm-config = "COOKBOOK_TOOLCHAIN/bin/llvm-config"

[target.x86_64-unknown-linux-gnu]
llvm-config = "COOKBOOK_TOOLCHAIN/bin/llvm-config"
